"""Business Agent planning models."""

from __future__ import annotations

from pydantic import BaseModel, Field

from src.agents.types import AgentType


class ExecutionPlan(BaseModel):
    """
    Execution workflow generated by the Business Planner.
    """

    agents: list[AgentType] = Field(
        default_factory=list,
    )

    parallel: bool = False

    reasoning: str | None = None