services:
  backend:
    build:
      context: ../../backend
      dockerfile: Dockerfile

    env_file:
      - ../../backend/.env.docker

    environment:
      ENVIRONMENT: development

    volumes:
      - ../../backend/src:/app/src
      - ../../backend/alembic:/app/alembic

    ports:
      - "8000:8000"

    command: >
      uvicorn
      src.main:app
      --host 0.0.0.0
      --port 8000
      --reload