services:

  postgres:
    image: postgres:17

    container_name: synapseos-postgres

    environment:
      POSTGRES_DB: synapseos
      POSTGRES_USER: synapseos
      POSTGRES_PASSWORD: synapseos

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio

    container_name: synapseos-minio

    restart: unless-stopped

    ports:
      - "9000:9000"
      - "9001:9001"

    environment:
      MINIO_ROOT_USER: synapseos
      MINIO_ROOT_PASSWORD: synapseos123

    command: server /data --console-address ":9001"

    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  minio_data: