"""Semantic layer schemas."""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel


class ColumnProfile(BaseModel):
    """
    Column level metadata.
    """

    name: str

    dtype: str

    samples: list[Any]


class TableProfile(BaseModel):
    """
    Dataset/table profile.
    """

    table_name: str

    columns: list[ColumnProfile]


class SemanticProfile(BaseModel):
    """
    Complete dataset profile.
    """

    tables: list[TableProfile]


class SemanticMapping(BaseModel):
    """
    Business understanding generated by LLM.
    """

    sales: dict[str, Any] = {}

    products: dict[str, Any] = {}

    customers: dict[str, Any] = {}

    sellers: dict[str, Any] = {}

    operations: dict[str, Any] = {}

    experience: dict[str, Any] = {}

    geography: dict[str, Any] = {}

    relationships: list[dict[str, Any]] = []

    unmapped: dict[str, Any] = {}