"""create forecast model

Revision ID: 2fbafeaa526c
Revises: d2cd00f374e8
Create Date: 2026-06-18 17:02:07.096462

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2fbafeaa526c'
down_revision: str | Sequence[str] | None = 'd2cd00f374e8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecast_models',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('date_column', sa.String(length=100), nullable=False),
    sa.Column('target_column', sa.String(length=100), nullable=False),
    sa.Column('artifact_path', sa.String(length=500), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecast_models_dataset_id'), 'forecast_models', ['dataset_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_forecast_models_dataset_id'), table_name='forecast_models')
    op.drop_table('forecast_models')
    # ### end Alembic commands ###
