"""create users table

Revision ID: 4da237685b04
Revises: 9f52d2d0df3a
Create Date: 2026-06-09 21:45:17.060362

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "4da237685b04"
down_revision: str | Sequence[str] | None = "9f52d2d0df3a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
