"""update forecast model

Revision ID: 6958163de555
Revises: 2fbafeaa526c
Create Date: 2026-06-19 00:48:16.584247

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6958163de555'
down_revision: str | Sequence[str] | None = '2fbafeaa526c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forecast_models', sa.Column('forecast_horizon', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forecast_models', 'forecast_horizon')
    # ### end Alembic commands ###
