"""add_training_group_to_ml_models

Revision ID: d2cd00f374e8
Revises: b79370bfb0d6
Create Date: 2026-06-17 16:58:42.886334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2cd00f374e8'
down_revision: Union[str, Sequence[str], None] = 'b79370bfb0d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ml_models', sa.Column('training_group', sa.Uuid(), nullable=False))
    op.add_column('ml_models', sa.Column('is_best', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_ml_models_training_group'), 'ml_models', ['training_group'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ml_models_training_group'), table_name='ml_models')
    op.drop_column('ml_models', 'is_best')
    op.drop_column('ml_models', 'training_group')
    # ### end Alembic commands ###
