"""upgrade forecast model metadata

Revision ID: d709699c5890
Revises: aed603d60cf7
Create Date: 2026-07-07 21:53:23.254778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd709699c5890'
down_revision: Union[str, Sequence[str], None] = 'aed603d60cf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forecast_models', sa.Column('aggregation', sa.String(length=50), nullable=False))
    op.add_column('forecast_models', sa.Column('frequency', sa.String(length=20), nullable=False))
    op.add_column('forecast_models', sa.Column('filters', sa.JSON(), nullable=True))
    op.add_column('forecast_models', sa.Column('business_question', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forecast_models', 'business_question')
    op.drop_column('forecast_models', 'filters')
    op.drop_column('forecast_models', 'frequency')
    op.drop_column('forecast_models', 'aggregation')
    # ### end Alembic commands ###
