"""Intelligence agent schemas."""

from __future__ import annotations

from pydantic import BaseModel

from src.mcp.types import MCPTool


class IntelligencePlan(BaseModel):
    """
    Execution plan generated by LLM.
    """

    tools: list[MCPTool]

    sections: list[str]

    reasoning: str