"""Generic dataset filtering service."""

from __future__ import annotations

import pandas as pd

from .schemas import DatasetFilters


class DatasetFilterService:
    """
    Generic dataset filtering service.

    Operates only on canonical feature columns produced by the
    Feature Builder.

    This service is shared across:
    - Analytics
    - Forecasting
    - Prediction
    - Risk
    - Scenario Analysis
    - AI Assistant
    """

    def apply(
        self,
        dataframe: pd.DataFrame,
        filters: DatasetFilters | None = None,
    ) -> pd.DataFrame:
        """
        Apply all supported filters to a canonical dataset.

        Parameters
        ----------
        dataframe:
            Canonical feature dataframe.

        filters:
            User supplied filter configuration.

        Returns
        -------
        pd.DataFrame
            Filtered dataframe.
        """

        if filters is None:
            return dataframe.copy()

        df = dataframe.copy()

        df = self._apply_date(df, filters)
        df = self._apply_location(df, filters)
        df = self._apply_category(df, filters)
        df = self._apply_brand(df, filters)
        df = self._apply_customer(df, filters)
        df = self._apply_seller(df, filters)
        df = self._apply_revenue(df, filters)
        df = self._apply_review_score(df, filters)

        return df

    # ------------------------------------------------------------------
    # Date
    # ------------------------------------------------------------------

    def _apply_date(
        self,
        dataframe: pd.DataFrame,
        filters: DatasetFilters,
    ) -> pd.DataFrame:
        """
        Filter dataframe by order date.

        Uses the canonical `order_date` column generated by the
        Feature Builder.
        """

        if "order_date" not in dataframe.columns:
            return dataframe

        df = dataframe.copy()

        df["order_date"] = pd.to_datetime(
            df["order_date"],
            errors="coerce",
        )

        if filters.date_from is not None:

            date_from = pd.to_datetime(
                filters.date_from,
                errors="coerce",
            )

            if pd.notna(date_from):
                df = df[
                    df["order_date"] >= date_from
                ]

        if filters.date_to is not None:

            date_to = pd.to_datetime(
                filters.date_to,
                errors="coerce",
            )

            if pd.notna(date_to):
                df = df[
                    df["order_date"] <= date_to
                ]

        return df

    # ------------------------------------------------------------------
    # Geography
    # ------------------------------------------------------------------

    def _apply_location(
        self,
        dataframe: pd.DataFrame,
        filters: DatasetFilters,
    ) -> pd.DataFrame:
        """
        Filter dataframe by state and city.

        Uses canonical columns generated by the
        Feature Builder.
        """

        df = dataframe.copy()

        # -------------------------
        # State
        # -------------------------

        if (
            "state" in df.columns
            and filters.states
        ):

            df = df[
                df["state"].isin(filters.states)
            ]

        # -------------------------
        # City
        # -------------------------

        if (
            "city" in df.columns
            and filters.city
        ):

            df = df[
                df["city"].isin(filters.city)
            ]

        return df

    # ------------------------------------------------------------------
    # Category
    # ------------------------------------------------------------------

    def _apply_category(
        self,
        dataframe: pd.DataFrame,
        filters: DatasetFilters,
    ) -> pd.DataFrame:
        """
        Filter dataframe by product category.

        Uses the canonical `category` column generated
        by the Feature Builder.
        """

        if (
            "category" not in dataframe.columns
            or not filters.categories
        ):
            return dataframe

        df = dataframe.copy()

        return df[
            df["category"].isin(filters.categories)
        ]

    # ------------------------------------------------------------------
    # Brand
    # ------------------------------------------------------------------

    def _apply_brand(
        self,
        dataframe: pd.DataFrame,
        filters: DatasetFilters,
    ) -> pd.DataFrame:
        """
        Filter dataframe by brand.

        Uses the canonical `brand` column generated
        by the Feature Builder.
        """

        if (
            "brand" not in dataframe.columns
            or not filters.brands
        ):
            return dataframe

        df = dataframe.copy()

        return df[
            df["brand"].isin(filters.brands)
        ]

    # ------------------------------------------------------------------
    # Customer
    # ------------------------------------------------------------------

    def _apply_customer(
        self,
        dataframe: pd.DataFrame,
        filters: DatasetFilters,
    ) -> pd.DataFrame:
        """
        Filter dataframe by customer.
        """

        if (
            "customer_id" not in dataframe.columns
            or not filters.customer_id
        ):
            return dataframe

        df = dataframe.copy()

        return df[
            df["customer_id"].isin(
                filters.customer_id
            )
        ]

    # ------------------------------------------------------------------
    # Seller
    # ------------------------------------------------------------------

    def _apply_seller(
        self,
        dataframe: pd.DataFrame,
        filters: DatasetFilters,
    ) -> pd.DataFrame:
        """
        Filter dataframe by seller.
        """

        if (
            "seller_id" not in dataframe.columns
            or not filters.seller_id
        ):
            return dataframe

        df = dataframe.copy()

        return df[
            df["seller_id"].isin(
                filters.seller_id
            )
        ]

    # ------------------------------------------------------------------
    # Revenue
    # ------------------------------------------------------------------

    def _apply_revenue(
        self,
        dataframe: pd.DataFrame,
        filters: DatasetFilters,
    ) -> pd.DataFrame:
        """
        Filter dataframe by revenue range.
        """

        if (
            "revenue" not in dataframe.columns
            or (
                filters.min_revenue is None
                and filters.max_revenue is None
            )
        ):
            return dataframe

        df = dataframe.copy()

        revenue = pd.to_numeric(
            df["revenue"],
            errors="coerce",
        )

        if filters.min_revenue is not None:
            df = df[
                revenue >= filters.min_revenue
            ]
            revenue = revenue.loc[df.index]

        if filters.max_revenue is not None:
            df = df[
                revenue <= filters.max_revenue
            ]

        return df

    # ------------------------------------------------------------------
    # Reviews
    # ------------------------------------------------------------------

    def _apply_review_score(
        self,
        dataframe: pd.DataFrame,
        filters: DatasetFilters,
    ) -> pd.DataFrame:
        """
        Filter dataframe by review score range.
        """

        if (
            "review_score" not in dataframe.columns
            or (
                filters.min_review_score is None
                and filters.max_review_score is None
            )
        ):
            return dataframe

        df = dataframe.copy()

        reviews = pd.to_numeric(
            df["review_score"],
            errors="coerce",
        )

        if filters.min_review_score is not None:
            df = df[
                reviews >= filters.min_review_score
            ]
            reviews = reviews.loc[df.index]

        if filters.max_review_score is not None:
            df = df[
                reviews <= filters.max_review_score
            ]

        return df