"""Forecast schemas."""

from __future__ import annotations

from pydantic import BaseModel



class ForecastPlan(BaseModel):
    """
    Forecast execution plan generated by LLM.
    """

    date_column: str | None = None

    target_column: str | None = None

    aggregation: str = "sum"

    frequency: str = "D"

    periods: int = 30

    filters: dict[str, str] = {}